## path to tools
# samTools:  /Users/koplev01/bin/samtools
# samTools:  /Users/koplev01/miniconda3/envs/titan/bin/samtools
samTools:  /Users/koplev01/miniconda3/envs/titan/bin/bcftools

## path to scripts ##
readCounterScript: /Users/koplev01/miniconda3/envs/titan/bin/readCounter
ichorCNA_rscript:  /Users/koplev01/projects/OVCT/ichorCNA/scripts/runIchorCNA.R
ichorCNA_libdir:  /Users/koplev01/projects/OVCT/ichorCNA
pyCountScript:  code/countPysam.py
TitanCNA_rscript: ../R_scripts/titanCNA.R
TitanCNA_selectSolutionRscript: ../R_scripts/selectSolution.R
TitanCNA_libdir:  ../..

## reference settings and paths to reference files ##
genomeBuild: hg19
genomeStyle:  NCBI  # UCSC or NCBI of output
refFasta:  /data/koplev01/genomes/human/Homo_sapiens.GRCh37.dna.primary_assembly.fa
snpVCF:  /data/koplev01/genomes/HapMap/hapmap_3.3.hg19.sites.chromNCBI.vcf.gz
ichorCNA_exons: /data/koplev01/genomes/exome/agilent/sureSelect_v4/S03723314_Covered_chromNCBI.bed
cytobandFile:  None # only need if hg38
centromere:  /Users/koplev01/projects/OVCT/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt
sex:  female   # use None if both females and males are in sample set

## standard parameters for qsub memory, runtime, pe (parallel environment)
# use what your scheduler designates for parameters; does not apply to local run
# invoke using:
# snakemake -s TitanCNA.snakefile --cluster-sync "qsub -l h_vmem={params.mem},h_rt={params.runtime} {params.pe}" -j 100 --jobscript config/cluster.sh
std_mem:  4G
std_runtime:  "05:00:00"  
std_numCores:  -pe smp 1 -binding linear:1

## params for each step ##

## read depth params ##
# use this for NCBI chr naming
chrs: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y 
# use this for UCSC chr naming
# chrs: chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrY 
binSize:  10000

## ichorCNA params ##
ichorCNA_gcWig: /Users/koplev01/projects/OVCT/ichorCNA/inst/extdata/gc_hg19_10kb.wig
ichorCNA_mapWig:  /Users/koplev01/projects/OVCT/ichorCNA/inst/extdata/map_hg19_10kb.wig
ichorCNA_chrs:  c(1:22, \"X\")
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)
ichorCNA_mem:  10G
ichorCNA_runtime:  "300:00:00"
ichorCNA_pe: -pe smp 1 -binding linear:1  

## allele counts - samtools, pysam ##
# USERS MUST MODIFY getAlleleCounts.snakefile to use the correct CHRS naming
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
# TitanCNA_maxNumClonalClusters: 2
TitanCNA_maxNumClonalClusters: 5
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 3
# TitanCNA_maxPloidy: 4
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
# TitanCNA_alphaK:  10000  # WGS
TitanCNA_alphaK:  2500  # WES
# TitanCNA_alphaR:  10000
TitanCNA_alphaR:  2500  # WES
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_numCores: 1
# TitanCNA_mem:  16G
TitanCNA_mem:  24G
TitanCNA_runtime:  "300:00:00"
TitanCNA_pe: -pe smp 1 -binding linear:1  
